name = "martin-wms"
main = "cloudflare/worker.js"
compatibility_date = "2026-04-10"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
preview_urls = true

[[routes]]
pattern = "kma-wms.com"
custom_domain = true

[[routes]]
pattern = "www.kma-wms.com"
custom_domain = true

[assets]
directory = "./frontend"
binding = "ASSETS"
not_found_handling = "single-page-application"

[vars]
SUPABASE_URL = "https://fvrvfioqfgvmvdgnniyu.supabase.co"
SUPABASE_PUBLISHABLE_KEY = "sb_publishable_s-f5r8mvwsUw2elcCidvgw_K0LawYRr"
